### ISSUE TITLE
Halfs not working

### ISSUE THREAD

**Issue by Flamekasai** [savurov/x7s#1]
When i bought it from the vendor and configured it with via it worked perfectly, then i changed keymap on a text editor and flashed with qmk and now only the split that is directly plugged by usb-c works, the other half doesnt work. Same with vial keymap.

Do you know what could be going on?

**Comment by savurov** [comment]
Has this issue been resolved? Did you try reflashing with the stock configuration?

**Comment by Flamekasai** [comment]
I resolved the issue flashing the firmware from [this commit](https://github.com/gleber/qmk_firmware/commit/54078ec73c0ff2bd01984242f748a837c1954d03) it is the only one that worked for me.
